server:
  port: 9999

spring:
  resources:
    static-locations: classpath:/static/,file:C:/Users/Aspiring/Desktop/upload/

  servlet:
    multipart:
      max-file-size: 10MB  # 单个文件的大小
      max-request-size: 100MB  # 上传文件的总大小

#eureka注册配置
eureka:
  client:
    register-with-eureka: true #为true表示把自己注册到服务端
    fetch-registry: true #是否抓取自己的注册信息，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/    #单机版
  instance:
    instance-id: FileSystem     #规定实例名，如过不写，则取application.name
    prefer-ip-address: true     #是否显示ip而不是 localhost:port
    lease-renewal-interval-in-seconds: 1      #每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-expiration-duration-in-seconds: 2   #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
